// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace ExploreLuxury.Infrastructure.Data.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class HotelEntryModification : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HotelEntryModification));
        
        string IMigrationMetadata.Id
        {
            get { return "201312090104466_HotelEntryModification"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
