// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace ExploreLuxury.Infrastructure.Data.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class AddRoomType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRoomType));
        
        string IMigrationMetadata.Id
        {
            get { return "201402051116411_AddRoomType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
