// <auto-generated />
namespace ExploreLuxury.Infrastructure.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class CityModelChanges_part2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CityModelChanges_part2));
        
        string IMigrationMetadata.Id
        {
            get { return "201402051416592_CityModelChanges_part2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
